
import { GoogleGenAI, Type } from "@google/genai";
import { CodeReviewResult } from "../types";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

const REVIEW_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    rating: {
      type: Type.STRING,
      description: "Code quality rating: Better, Good, Normal, or Bad",
    },
    summary: {
      type: Type.STRING,
      description: "Short overview of the code quality",
    },
    explanation: {
      type: Type.STRING,
      description: "Step-by-step explanation of what the code does",
    },
    issues: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          title: { type: Type.STRING },
          type: { type: Type.STRING, description: "bug | style | performance | security | readability | other" },
          description: { type: Type.STRING },
          fixExample: { type: Type.STRING }
        },
        required: ["title", "type", "description", "fixExample"]
      }
    },
    suggestions: {
      type: Type.ARRAY,
      items: { type: Type.STRING }
    },
    improvedCode: {
      type: Type.STRING,
      description: "The full improved version of the source code"
    },
    aiUsagePercentage: {
      type: Type.NUMBER,
      description: "An estimated percentage (0-100) of how likely this code was generated by an AI model"
    },
    originAnalysis: {
      type: Type.STRING,
      description: "A brief justification for the AI usage percentage"
    }
  },
  required: ["rating", "summary", "explanation", "issues", "suggestions", "improvedCode", "aiUsagePercentage", "originAnalysis"]
};

export const reviewCode = async (code: string, language: string): Promise<CodeReviewResult> => {
  const prompt = `STRICT SYSTEM INSTRUCTION:
You are a senior elite developer. You must perform a logical audit of the PROVIDED CODE below.

RULES:
1. ONLY analyze the code snippet provided. 
2. If the code is minimal (e.g., a single print statement), do NOT invent complex bugs.
3. If the code is syntactically invalid for ${language} (e.g. using 'print' in JavaScript instead of 'console.log'), identify that as a primary error.
4. Be honest about AI usage: high-quality generic boilerplate is usually AI; unique, specific, or non-standard code is usually Human.

PROVIDED CODE (${language}):
"""
${code}
"""
`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        thinkingConfig: { thinkingBudget: 4000 },
        responseMimeType: "application/json",
        responseSchema: REVIEW_SCHEMA,
      },
    });

    if (!response.text) {
      throw new Error("No response from AI");
    }

    return JSON.parse(response.text) as CodeReviewResult;
  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};
